# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: [--autofix]
    exclude_types: [jupyter]
  - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs
    exclude_types: [makefile, batch]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]
  - id: pretty-format-toml
    args: [--autofix, --trailing-commas]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    exclude: ".cruft.json|tests/data"
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.2
  hooks:
  - id: ruff
    args: [--exclude, docs/**]
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.2.25
  hooks:
  - id: pip-compile
    args: [pyproject.toml, --extra=service, -o, requirements.txt, --python-version, "3.12"]
    files: ^pyproject.toml$
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.2.25
  hooks:
  - id: pip-compile
    args: [pyproject.toml, --extra=tests, -o, test_requirements.txt, --python-version, "3.12"]
    files: ^pyproject.toml$
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
