[GLOBAL]
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.build_files.fmt.ruff",
  "pants.backend.docker",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell"
]
pants_ignore_use_gitignore = false
pants_version = "2.23.0"

[python]
interpreter_constraints = ['==3.12.*']

[source]
root_patterns = [
  '/src',
  '/src/services',
]
